[project]
name = "magm-edge-server"
version = "0.1.0"
description = ""
authors = [
    {name = "Daniel24125",email = "danielmadalena@msn.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paho-mqtt (>=2.1.0,<3.0.0)",
    "boto3 (>=1.40.56,<2.0.0)",
    "sqlite-utils (>=3.38,<4.0)",
    "apscheduler (>=3.11.0,<4.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "pydantic (>=2.12.3,<3.0.0)",
    "typing-extensions (>=4.15.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
