version = 0.1

[default.deploy.parameters]
stack_name = "UM-MAGM-IoT-Lambda"
resolve_s3 = true
s3_prefix = "UM-MAGM-IoT-Lambda"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-3"
